=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/presentation.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="element" type="elementType"/>
    <xs:complexType name="parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="elementType" mixed="true">
        <xs:sequence>
            <xs:element type="xs:string" name="description" minOccurs="0"/>
            <xs:element type="referencesType" name="references" minOccurs="0"/>
            <xs:element type="parametersType" name="parameters" minOccurs="0"/>
            <xs:element type="xs:string" name="examples" minOccurs="0"/>
            <xs:element type="xs:string" name="notes" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="referenceComponentType" mixed="true">
        <xs:attribute type="xs:string" name="library" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element type="parameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="referencesType">
        <xs:sequence>
            <xs:element type="referenceComponentType" name="component" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="urlType" name="url" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="link" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== JetBrains/intellij-obsolete-plugins/tapestry/src/main/java/documentation/core/components/PageLink.xml
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../presentation.xsd">
    <description>
        Generates a render request link to some other page in the application. If an activation context is supplied (as the context parameter), then the context values will be encoded into the\
        URL. If no context is supplied, then the target page itself will supply the context via a passivate event. Pages are not required to have an activation context. When a page does have an\
        activation context, the value typically represents the identity of some object displayed or otherwise manipulated by the page.
    </description>

    <parameters>
        <parameter name="anchor">
            An anchor value to append to the generated URL (the hash separator will be added automatically).
        </parameter>
        <parameter name="context">
            If provided, this is the activation context for the target page (the information will be encoded into the URL). If not provided, then the target page will provide its own activation\
            context.
        </parameter>
        <parameter name="disabled">
            If true, then then no link element is rendered (and no informal parameters as well). The body is, however, still rendered.
        </parameter>
        <parameter name="page">
            The logical name of the page to link to.
        </parameter>
    </parameters>

    <examples>
        <![CDATA[
<p>
    This will be a set of examples about PageLink.
</p>
	]]>
    </examples>

    <notes>
        <![CDATA[
<p>
    This will be more notes about PageLink.
</p>
	]]>
    </notes>
</element>
